"""Adapters between existing geometric path segments and CROWN route columns."""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass, replace
from typing import Dict, Mapping, Optional, Sequence, Tuple

from ..resources import stable_resource_id
from ..types import (
    AgentPathPlan,
    MultiAgentPathPlan,
    PaperReference,
    PathPlanningConfig,
    PathSegmentSpec,
    PathWaypoint,
)
from .types import CrownBpcSolution, CrownInstance, CrownOperation, CrownRoute


@dataclass(frozen=True)
class CrownSegmentRouteCandidate:
    """One geometric route candidate before conversion to a CROWN column."""

    route_id: str
    task_ids: Tuple[str, ...]
    segments: Tuple[PathSegmentSpec, ...]
    mode_ids: Tuple[str, ...] = ()


def _segment_duration(segment: PathSegmentSpec, fallback_speed: float) -> float:
    timed = [waypoint.time for waypoint in segment.waypoints if waypoint.time is not None]
    if len(timed) >= 2 and timed[-1] > timed[0]:
        return float(timed[-1] - timed[0])
    if segment.length > 0.0:
        return float(segment.length / fallback_speed)
    raise ValueError(f"segment {segment.segment_id!r} has neither duration nor length")


def crown_route_from_path_segments(
    agent_id: int,
    candidate: CrownSegmentRouteCandidate,
    path_config: PathPlanningConfig,
    *,
    fallback_speed: float = 1.0,
    energy_per_meter: float = 1.0,
    energy_per_second: float = 0.0,
) -> CrownRoute:
    """Convert an existing collision-free single-agent route into one column."""

    if fallback_speed <= 0.0:
        raise ValueError("fallback_speed must be positive")
    if energy_per_meter < 0.0 or energy_per_second < 0.0:
        raise ValueError("energy proxy coefficients must be non-negative")
    segments = tuple(deepcopy(candidate.segments))
    operations = []
    for index, segment in enumerate(segments):
        duration = _segment_duration(segment, fallback_speed)
        resource_id = stable_resource_id(segment, path_config)
        operations.append(
            CrownOperation(
                operation_id=f"segment-{index}:{segment.segment_id}",
                duration=duration,
                resource_ids=(resource_id,),
                energy=(
                    energy_per_meter * max(segment.length, 0.0)
                    + energy_per_second * duration
                ),
                kind=segment.kind,
                metadata={"segment_id": segment.segment_id},
            )
        )
    return CrownRoute(
        route_id=f"agent-{agent_id}:{candidate.route_id}",
        agent_id=str(agent_id),
        task_ids=tuple(candidate.task_ids),
        operations=tuple(operations),
        mode_ids=tuple(candidate.mode_ids),
        metadata={"path_segments": segments, "source": "existing-path-segments"},
    )


def build_crown_instance_from_segment_candidates(
    agent_ids: Sequence[int],
    task_ids: Sequence[str],
    candidates_by_agent: Mapping[int, Sequence[CrownSegmentRouteCandidate]],
    path_config: PathPlanningConfig,
    *,
    fallback_speed: float = 1.0,
    energy_per_meter: float = 1.0,
    energy_per_second: float = 0.0,
    wait_energy_per_second: float = 0.0,
) -> CrownInstance:
    """Build the exact-core input from geometry generated by the current stack."""

    routes_by_agent = {}
    for agent_id in agent_ids:
        candidates = candidates_by_agent.get(agent_id, ())
        routes_by_agent[str(agent_id)] = tuple(
            crown_route_from_path_segments(
                agent_id,
                candidate,
                path_config,
                fallback_speed=fallback_speed,
                energy_per_meter=energy_per_meter,
                energy_per_second=energy_per_second,
            )
            for candidate in candidates
        )
    return CrownInstance(
        agent_ids=tuple(str(agent_id) for agent_id in agent_ids),
        task_ids=tuple(task_ids),
        routes_by_agent=routes_by_agent,
        resource_separation=path_config.resource_separation_time,
        wait_energy_rates={
            str(agent_id): wait_energy_per_second for agent_id in agent_ids
        },
        metadata={"source": "path-planning-segment-candidates"},
    )


def _retime_segment(
    segment: PathSegmentSpec,
    new_start: float,
    physical_duration: float,
) -> PathSegmentSpec:
    cloned = deepcopy(segment)
    if not cloned.waypoints:
        return cloned
    original_times = [waypoint.time for waypoint in cloned.waypoints]
    if all(value is not None for value in original_times):
        origin = float(original_times[0])
        relative = [float(value) - origin for value in original_times]
    elif len(cloned.waypoints) == 1:
        relative = [0.0]
    else:
        relative = [
            physical_duration * index / (len(cloned.waypoints) - 1)
            for index in range(len(cloned.waypoints))
        ]
    cloned.waypoints = [
        replace(waypoint, time=new_start + relative_time)
        for waypoint, relative_time in zip(cloned.waypoints, relative)
    ]
    cloned.metadata = dict(cloned.metadata)
    cloned.metadata["crown_retimed"] = "true"
    return cloned


def bpc_solution_to_path_plan(
    solution: CrownBpcSolution,
    *,
    agent_id_lookup: Optional[Mapping[str, int]] = None,
    paper_references: Sequence[PaperReference] = (),
) -> MultiAgentPathPlan:
    """Materialize selected timed columns as the project's path-plan schema."""

    lookup = dict(agent_id_lookup or {})
    agents: Dict[int, AgentPathPlan] = {}
    for ordinal, timed_route in enumerate(
        sorted(solution.timed_routes, key=lambda route: route.agent_id)
    ):
        if timed_route.agent_id in lookup:
            numeric_agent_id = lookup[timed_route.agent_id]
        else:
            try:
                numeric_agent_id = int(timed_route.agent_id)
            except ValueError:
                numeric_agent_id = ordinal
        stored_segments = tuple(timed_route.base_route.metadata.get("path_segments", ()))
        if len(stored_segments) != len(timed_route.start_slots):
            raise ValueError(
                "selected route lacks the geometric segments required for materialization"
            )
        segments = []
        for segment, operation, start_slot, duration_slots in zip(
            stored_segments,
            timed_route.base_route.operations,
            timed_route.start_slots,
            timed_route.duration_slots,
        ):
            retimed = _retime_segment(
                segment,
                start_slot * timed_route.time_step,
                operation.duration,
            )
            segments.append(retimed)
            allocated_end = (start_slot + duration_slots) * timed_route.time_step
            physical_end = start_slot * timed_route.time_step + operation.duration
            slack = allocated_end - physical_end
            if slack <= 1.0e-9 or not retimed.waypoints:
                continue
            endpoint = retimed.waypoints[-1]
            segments.append(
                PathSegmentSpec(
                    segment_id=f"{segment.segment_id}:rounding-wait",
                    kind="wait",
                    source_algorithm="crown_mcpp",
                    waypoints=[
                        replace(endpoint, time=physical_end, speed=0.0),
                        replace(endpoint, time=allocated_end, speed=0.0),
                    ],
                    length=0.0,
                    path_source="time_grid_rounding_wait",
                    metadata={
                        "crown_retimed": "true",
                        "rounding_wait": "true",
                        "rounding_wait_duration": f"{slack:.12g}",
                    },
                )
            )
        agents[numeric_agent_id] = AgentPathPlan(
            agent_id=numeric_agent_id,
            source_algorithm="crown_bpc_minimal_exact",
            segments=segments,
            metrics={
                "total_length": sum(segment.length for segment in segments),
                "estimated_time": timed_route.finish_time,
                "total_energy": timed_route.energy,
            },
            paper_references=list(paper_references),
        )

    return MultiAgentPathPlan(
        algorithm_name="crown_bpc_minimal_exact",
        agents=agents,
        metadata={
            "status": "finite_time_expanded_global_optimum",
            "makespan": f"{solution.makespan:.9f}",
            "total_energy": f"{solution.total_energy:.9f}",
            "lower_bound": f"{solution.lower_bound:.9f}",
            "upper_bound": f"{solution.upper_bound:.9f}",
            "optimality_gap": f"{solution.optimality_gap:.9f}",
            "energy_lower_bound": f"{solution.energy_lower_bound:.9f}",
            "energy_upper_bound": f"{solution.energy_upper_bound:.9f}",
            "energy_optimality_gap": f"{solution.energy_optimality_gap:.9f}",
            "time_step": f"{solution.time_step:.9f}",
            "generated_columns": str(solution.generated_columns),
            "pricing_iterations": str(solution.pricing_iterations),
            "branch_nodes": str(solution.branch_nodes),
            "resource_precedence_branches": str(
                solution.resource_precedence_branches
            ),
            "route_variable_branches": str(solution.route_variable_branches),
            "conflict_separation_rounds": str(solution.conflict_separation_rounds),
        },
        paper_references=list(paper_references),
    )
